name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package shade:shade -DskipTests

    - name: Debug JAR contents
      run: |
        cd target
        echo "JAR size:"
        ls -lh autoblog4-1.0-SNAPSHOT.jar
        echo "Listing key classes:"
        jar tvf autoblog4-1.0-SNAPSHOT.jar | grep -i contentgeneration

    - name: Run tests
      run: mvn test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Debug and Zip JAR for Lambda
      run: |
        cd target
        echo "Original JAR size:"
        ls -lh autoblog4-1.0-SNAPSHOT.jar
        
        # Create a proper directory structure in the zip
        mkdir -p com/zho/services/DailyPosts/lambda
        cp autoblog4-1.0-SNAPSHOT.jar com/zho/services/DailyPosts/lambda/
        
        # Create the zip with the directory structure
        zip -r function.zip com/
        
        echo "Zip contents:"
        unzip -l function.zip

    - name: Upload to S3 and update Lambda
      run: |
        echo "Uploading to S3..."
        aws s3 cp target/function.zip s3://autoblog-lambda-deployment/function.zip
        
        echo "Updating Lambda from S3..."
        aws lambda update-function-code \
          --function-name PostGenerationFunction \
          --s3-bucket autoblog-lambda-deployment \
          --s3-key function.zip